name: Java CI v3 Packaging

on: 
  pull_request:
    branches:  
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          java-version: '11'
          distribution: 'adopt'
      - run: |
         mvn --batch-mode --update-snapshots verify
         mkdir staging && cp target/*.jar staging
      - name: Package and upload artifact  
        uses: actions/upload-artifact@v2
        with:
          name: Package
          path: staging
